/**
 * The two colours the logo is made of.
 *
 * Written as hex, and deliberately not referencing the navy ramp: these have to
 * stay byte-identical to the committed artwork in `assets/brand/*.svg`, which is
 * generated by `scripts/brand/` and knows nothing about this file. If the mark is
 * ever recut, these move with it — see `specs/brand.md`.
 */
export const BrandColors = {
  navy: '#000036', // navy-950, the logo ground
  ink: '#FFFFFF', // the only ink in the mark
} as const;

/** Imperative color constants for RN props that don't accept Tailwind class names. */
export const Colors = {
  /**
   * navy-600, not the brand navy-950. The logo ground sits at 10.6% lightness,
   * which reads as a black slab on a button rather than something tappable;
   * 600 stays unmistakably the brand hue while looking interactive. Carries
   * white at 10.5:1.
   */
  primary: 'hsl(240 55% 40%)', // navy-600
  primaryForeground: 'hsl(240 20% 97.5%)', // slate-50
  /** slate-400 clears the 3.0 non-text bar against slate-50 at 3.23:1. */
  tabIconDefault: 'hsl(240 11% 58%)', // slate-400
  text: 'hsl(240 30% 8%)', // slate-950
  destructive: 'hsl(354 74% 36%)', // error-600
  error: 'hsl(354 80% 26%)', // error-800

  /**
   * Icon colours. `AppIcon` paints through an SVG `fill` prop rather than a
   * class name, so icon colour cannot come from Tailwind and has to live here.
   *
   * Before the navy identity these were stock Tailwind greys hard-coded at
   * ~50 call sites (`#374151`, `#9CA3AF`, `#D1D5DB`) alongside the old accent
   * `#4B7A6E`, which meant the palette was only half in the token layer. Add
   * new icon shades here rather than reaching for a literal.
   */
  icon: 'hsl(240 15% 28%)', // slate-700 — default and inactive icons
  iconMuted: 'hsl(240 11% 58%)', // slate-400 — secondary icons, muted captions
  iconDisabled: 'hsl(240 13% 78%)', // slate-300 — empty-state artwork
} as const;

/**
 * Intensity ramp for the practice heatmap: a light navy tint for a little
 * practice up to the darkest brand shade for the most. `empty` is the neutral
 * cell for days with no practice, tinted to sit on the slate-50 background.
 *
 * Kept on the brand hue so the grid reads as part of the app's palette rather
 * than a library default. `headerText` matches the muted captions used
 * elsewhere on the dashboard so the month labels sit in the same palette.
 *
 * The four steps are spaced so each is at least 1.25:1 against its neighbour,
 * and `empty` is at least that far from the first filled step — otherwise a
 * one-minute day and a no-practice day look identical at cell size. Measured
 * separations: empty>1 1.34, 1>2 2.40, 2>3 2.83, 3>4 1.63. Re-check these if
 * any step moves.
 */
export const HeatmapColors = {
  empty: 'hsl(240 18% 94.5%)', // slate-100
  headerText: 'hsl(240 11% 58%)', // slate-400
  ramp: [
    'hsl(240 50% 87%)', // navy-200
    'hsl(240 42% 64%)', // navy-400
    'hsl(240 55% 40%)', // navy-600 (app accent)
    'hsl(240 82% 21%)', // navy-800
  ],
} as const;

/**
 * Categorical palette for the PlayView section label — one entry per section,
 * assigned by `domain/sections.ts#assignSectionColorIndices`.
 *
 * Deliberately outside the navy/slate brand ramps: these hues carry information
 * rather than decoration. A student glancing at the label needs to tell "this is a
 * different section from the last one" at a distance, and tints of one hue cannot
 * do that. Hues are spread around the wheel and ordered so that neighbours in the
 * cycle are far apart.
 *
 * These survived the move to the navy identity untouched, and should keep surviving
 * rebrands: they encode data, so matching them to the brand would actively damage
 * them. One consequence worth knowing — the `blue` entry (hue 214) now sits nearer
 * the brand hue (240) than it did to the old seagrass. They stay tellable apart
 * because section labels only ever appear on light PlayView surfaces, never against
 * navy chrome. If that ever stops being true, re-check `blue` first.
 *
 * Every entry is generated straight off the section hue ramp (`domain/oklch.ts`,
 * L 0.78 / C 0.15, one hue per slot), which the color picker also draws from. Keeping
 * both on the same ramp is what stops a hand-picked color and a preset from looking
 * like they came from different palettes, and holding one OKLCH lightness across the
 * circle is what stops any single hue reading heavier than its neighbours. Any hue
 * added here should be generated the same way rather than typed in.
 *
 * The label draws **white** text on these, which is roughly 2:1 — under the WCAG floor
 * for large text, and deliberately so. Black is comfortably legible on them but reads
 * heavy; the color is what carries which section is running, and the name is a
 * glance-level cue rather than a paragraph. Nothing about this palette guarantees the
 * text is readable, and that is a decision about the text, not about these values.
 *
 * Written as hex rather than the `hsl(H S% L%)` used elsewhere in this file, because
 * these strings cross three different color parsers: React Native styles, the
 * `react-native-svg` gradient stops behind the label, and CSS gradients inside the
 * WebView, which receives them verbatim over SET_SECTIONS. Hex is the only notation
 * all three parse identically. The source hue is kept in the comment.
 *
 * Not migrated: a piece imported before this palette landed keeps the darker color it
 * stored, and will show black text on it until the user edits or re-imports it.
 */
export const SectionColors: readonly string[] = [
  '#8BB9FF', // blue — h 259, 10.5:1 on black
  '#FF977F', // vermilion — h 34, 10.0:1
  '#5DD38A', // green — h 154, 11.2:1
  '#CD9FFF', // violet — h 305, 10.0:1
  '#F9A140', // amber — h 64, 10.2:1
  '#FF8FB6', // magenta — h 359, 9.9:1
  '#00CDEA', // teal — h 212, 10.9:1
  '#92CB62', // olive — h 133, 10.9:1
] as const;
