import esbuild from 'esbuild';
import { writeFileSync, mkdirSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const HTML_TEMPLATE = `<!DOCTYPE html>
<html><head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <style>body { margin: 0; background: white; } #osmd { width: 100%; }</style>
</head><body>
  <div id="osmd"></div>
  <script>
    window.onerror = function(msg, _src, line, col) {
      window.ReactNativeWebView && window.ReactNativeWebView.postMessage(
        JSON.stringify({ type: 'DEBUG', payload: 'SCRIPT ERR: ' + msg + ' @' + line + ':' + col })
      );
    };
  </script>
  <script>/* BUNDLE_PLACEHOLDER */</script>
</body></html>`;

const result = await esbuild.build({
  entryPoints: [resolve(__dirname, 'src/index.ts')],
  bundle: true,
  format: 'iife',
  target: ['chrome58'],
  minify: true,
  write: false,
  platform: 'browser',
  treeShaking: true,
  logLevel: 'info',
});

const bundleText = result.outputFiles[0].text;
// Use a function so $& and other $ patterns in bundleText aren't treated as
// replacement specifiers by String.prototype.replace.
const html = HTML_TEMPLATE.replace('/* BUNDLE_PLACEHOLDER */', () => bundleText);

// Escape for embedding in a TypeScript template literal.
// Backslashes first — order matters to avoid double-escaping.
const escaped = html
  .replace(/\\/g, '\\\\')
  .replace(/`/g, '\\`')
  .replace(/\$\{/g, '\\${');

const outDir = resolve(__dirname, '../src/score-web');
mkdirSync(outDir, { recursive: true });

const outPath = resolve(outDir, 'html.ts');
writeFileSync(
  outPath,
  `// AUTO-GENERATED by score-web/build.mjs — do not edit by hand.\n` +
    `// Run: npm run build:score-web\n` +
    `export const SCORE_WEB_HTML = \`${escaped}\`;\n`,
  'utf8',
);

console.log('score-web build complete →', outPath);
