import esbuild from 'esbuild';
import { writeFileSync, mkdirSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const HTML_TEMPLATE = `<!DOCTYPE html>
<html><head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <style>
    html, body { margin: 0; overflow: hidden; width: 100%; height: 100%; background: white; user-select: none; -webkit-user-select: none; }
    #cursor-line {
      position: fixed; left: 50%; top: 0; height: 100%; width: 2px;
      background: #4B7A6E; pointer-events: none; z-index: 20;
      transform: translateX(-50%);
    }
    #osmd-wrapper {
      position: fixed; top: 0; left: 0; width: 100%; height: 100%; overflow: hidden;
    }
    #osmd { position: absolute; top: 0; left: 0; will-change: transform; }
    #loop-shade {
      position: absolute; top: 0;
      background: rgba(100,149,237,0.20); pointer-events: none; display: none;
    }
    .loop-handle {
      position: absolute; top: 0; width: 28px;
      background: rgba(75,122,110,0.75); cursor: ew-resize;
      touch-action: none; display: none; z-index: 10;
      align-items: center; justify-content: center;
    }
    .loop-handle svg { pointer-events: none; flex-shrink: 0; }
  </style>
</head><body>
  <div id="cursor-line"></div>
  <div id="osmd-wrapper">
    <div id="osmd">
      <div id="loop-shade"></div>
      <div id="loop-handle-a" class="loop-handle"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="32" height="32"><path fill="#4B7A6E" d="M9,3H11V5H9V3M13,3H15V5H13V3M9,7H11V9H9V7M13,7H15V9H13V7M9,11H11V13H9V11M13,11H15V13H13V11M9,15H11V17H9V15M13,15H15V17H13V15M9,19H11V21H9V19M13,19H15V21H13V19Z"/></svg></div>
      <div id="loop-handle-b" class="loop-handle"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="32" height="32"><path fill="#4B7A6E" d="M9,3H11V5H9V3M13,3H15V5H13V3M9,7H11V9H9V7M13,7H15V9H13V7M9,11H11V13H9V11M13,11H15V13H13V11M9,15H11V17H9V15M13,15H15V17H13V15M9,19H11V21H9V19M13,19H15V21H13V19Z"/></svg></div>
    </div>
  </div>
  <script>
    window.onerror = function(msg, _src, line, col) {
      window.ReactNativeWebView && window.ReactNativeWebView.postMessage(
        JSON.stringify({ type: 'DEBUG', payload: 'SCRIPT ERR: ' + msg + ' @' + line + ':' + col })
      );
    };
  </script>
  <script>/* BUNDLE_PLACEHOLDER */</script>
</body></html>`;

const result = await esbuild.build({
  entryPoints: [resolve(__dirname, 'src/index.ts')],
  bundle: true,
  format: 'iife',
  target: ['chrome58'],
  minify: true,
  write: false,
  platform: 'browser',
  // Prefer the ESM 'module' field over the 'browser' field.
  // Tone.js sets browser=build/Tone.js (UMD, no named exports) but
  // module=build/esm/index.js (ESM, named exports). esbuild's default
  // platform:browser ordering picks the UMD bundle, breaking imports.
  mainFields: ['module', 'main'],
  treeShaking: true,
  logLevel: 'info',
});

const bundleText = result.outputFiles[0].text;
// Use a function so $& and other $ patterns in bundleText aren't treated as
// replacement specifiers by String.prototype.replace.
const html = HTML_TEMPLATE.replace('/* BUNDLE_PLACEHOLDER */', () => bundleText);

// Escape for embedding in a TypeScript template literal.
// Backslashes first — order matters to avoid double-escaping.
const escaped = html
  .replace(/\\/g, '\\\\')
  .replace(/`/g, '\\`')
  .replace(/\$\{/g, '\\${');

const outDir = resolve(__dirname, '../src/score-web');
mkdirSync(outDir, { recursive: true });

const outPath = resolve(outDir, 'html.ts');
writeFileSync(
  outPath,
  `// AUTO-GENERATED by score-web/build.mjs — do not edit by hand.\n` +
    `// Run: npm run build:score-web\n` +
    `export const SCORE_WEB_HTML = \`${escaped}\`;\n`,
  'utf8',
);

console.log('score-web build complete →', outPath);
